modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "https://github.com/SaltSouls/Calm-Mornings"
    updateJSONURL = "https://www.curseforge.com/minecraft/mc-mods/calm-mornings"
    logoFile = "banner.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
[modproperties."${mod_id}"]
    catalogueImageIcon="icon.png"
    catalogueBackground="background.png"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    ide = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
[[dependencies."${mod_id}"]]
    modId = "sleep_tight"
    mandatory = false
    versionRange = "${sleeptight_version_range}"
    ordering = "AFTER"