modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL="https://github.com/SaltSouls/Calm-Mornings/issues"
[[mods]]
modId = "calmmornings"
version = "${file.jarVersion}"
displayName = "Calm Mornings"
logoFile="banner.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/calm-mornings"
description = '''
Despawns hostile entities in a configurable radius around the player upon waking. No more stressful mornings worrying about creepers lurking outside your front door.'''
authors = "TwinSouls"
credits="Kreezxil, MacTso, vectorwing"
[modproperties.calmmornings]
catalogueImageIcon = "icon.png"
[[dependencies.calmmornings]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.calmmornings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
