modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/SaltSouls/Calm-Mornings/issues"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "https://github.com/SaltSouls/Calm-Mornings"
    updateJSONURL = "https://modrinth.com/mod/calm-mornings"
    logoFile = "banner.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
# Catalogue compat
[modproperties."${mod_id}"]
    catalogueImageIcon="icon.png"
    catalogueBackground="background.png"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "sleep_tight"
    type = "optional"
    versionRange = "${st_version_range}"
    ordering = "AFTER"
    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features."${mod_id}"]
#openGLVersion="[3.2,)"
